spring:
  datasource:
    url: jdbc:postgresql://postgres-event-booking-89:5432/room-service
    username: admin
    password: password
  flyway:
    enabled: true
    locations: classpath:db/migration
