spring:
  datasource:
    url: jdbc:postgresql://postgres-event-booking:5432/approval-service
    username: admin
    password: password
  flyway:
    enabled: true
    locations: classpath:db/migration
